<a href="https://colab.research.google.com/github/rifda83/kkpm-assignments/blob/main/Tugas1_MLP_Rifda_Sasmi_Zahra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neural_network import MLPClassifier, MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in /usr/local/lib/python3.12/dist-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.12/dist-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)

In [ ]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
breast_cancer_wisconsin_original = fetch_ucirepo(id=15)

# data (as pandas dataframes)
X = breast_cancer_wisconsin_original.data.features
y = breast_cancer_wisconsin_original.data.targets

# metadata
print(breast_cancer_wisconsin_original.metadata)

# variable information
print(breast_cancer_wisconsin_original.variables)

{'uci_id': 15, 'name': 'Breast Cancer Wisconsin (Original)', 'repository_url': 'https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original', 'data_url': 'https://archive.ics.uci.edu/static/public/15/data.csv', 'abstract': 'Original Wisconsin Breast Cancer Database', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 699, 'num_features': 9, 'feature_types': ['Integer'], 'demographics': [], 'target_col': ['Class'], 'index_col': ['Sample_code_number'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1990, 'last_updated': 'Sun Mar 10 2024', 'dataset_doi': '10.24432/C5HP4Z', 'creators': ['WIlliam Wolberg'], 'intro_paper': None, 'additional_info': {'summary': "Samples arrive periodically as Dr. Wolberg reports his clinical cases. The database therefore reflects this chronological grouping of the data. This grouping information appears immediately below, having been removed from the data itself:\r\n\r\nGroup 1: 367 instances (January 1989)\r\nGroup 2:  70 instances (October 1989)\r\nGroup 3:  31 instances (February 1990)\r\nGroup 4:  17 instances (April 1990)\r\nGroup 5:  48 instances (August 1990)\r\nGroup 6:  49 instances (Updated January 1991)\r\nGroup 7:  31 instances (June 1991)\r\nGroup 8:  86 instances (November 1991)\r\n-----------------------------------------\r\nTotal:   699 points (as of the donated datbase on 15 July 1992)\r\n\r\nNote that the results summarized above in Past Usage refer to a dataset of size 369, while Group 1 has only 367 instances.  This is because it originally contained 369 instances; 2 were removed.  The following statements summarizes changes to the original Group 1's set of data:\r\n\r\n#####  Group 1 : 367 points: 200B 167M (January 1989)\r\n\r\n#####  Revised Jan 10, 1991: Replaced zero bare nuclei in 1080185 & 1187805\r\n\r\n#####  Revised Nov 22,1991: Removed 765878,4,5,9,7,10,10,10,3,8,1 no record\r\n#####                  : Removed 484201,2,7,8,8,4,3,10,3,4,1 zero epithelial\r\n#####                  : Changed 0 to 1 in field 6 of sample 1219406\r\n#####                  : Changed 0 to 1 in field 8 of following sample:\r\n#####                  : 1182404,2,3,1,1,1,2,0,1,1,1", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '1. Sample code number:            id number\r\n2. Clump Thickness:               1 - 10\r\n3. Uniformity of Cell Size:       1 - 10\r\n4. Uniformity of Cell Shape:      1 - 10\r\n5. Marginal Adhesion:             1 - 10\r\n6. Single Epithelial Cell Size:   1 - 10\r\n7. Bare Nuclei:                   1 - 10\r\n8. Bland Chromatin:               1 - 10\r\n9. Normal Nucleoli:               1 - 10\r\n10. Mitoses:                       1 - 10\r\n11. Class:                        (2 for benign, 4 for malignant)', 'citation': 'This breast cancer databases was obtained from the University of Wisconsin Hospitals, Madison from Dr. William H. Wolberg.  If you publish results when using this database, then please include this information in your acknowledgements.  Also, please cite one or more of:\n1. O. L. Mangasarian and W. H. Wolberg: "Cancer diagnosis via linear programming", SIAM News, Volume 23, Number 5, September 1990, pp 1 & 18.\n2. William H. Wolberg and O.L. Mangasarian: "Multisurface method of pattern separation for medical diagnosis applied to breast cytology", Proceedings of the National Academy of Sciences, U.S.A., Volume 87, December 1990, pp 9193-9196.\n3. O. L. Mangasarian, R. Setiono, and W.H. Wolberg: "Pattern recognition via linear programming: Theory and application to medical diagnosis", in: "Large-scale numerical optimization", Thomas F. Coleman and Yuying Li, editors, SIAM Publications, Philadelphia 1990, pp 22-30.\n4. K. P. Bennett & O. L. Mangasarian: "Robust linear programming discrimination of two linearly inseparable sets", Optimization Methods and Software 1, 1992, 23-34 (Gordon & Breach Science Publishers).'}}
                           name     role         type demographic  \
0            Sample_code_number       ID  Categorical        None
1               Clump_thickness  Feature      Integer        None
2       Uniformity_of_cell_size  Feature      Integer        None
3      Uniformity_of_cell_shape  Feature      Integer        None
4             Marginal_adhesion  Feature      Integer        None
5   Single_epithelial_cell_size  Feature      Integer        None
6                   Bare_nuclei  Feature      Integer        None
7               Bland_chromatin  Feature      Integer        None
8               Normal_nucleoli  Feature      Integer        None
9                       Mitoses  Feature      Integer        None
10                        Class   Target       Binary        None

                  description units missing_values
0                        None  None             no
1                        None  None             no
2                        None  None             no
3                        None  None             no
4                        None  None             no
5                        None  None             no
6                        None  None            yes
7                        None  None             no
8                        None  None             no
9                        None  None             no
10  2 = benign, 4 = malignant  None             no

In [ ]:
combined_data = pd.concat([X, y], axis=1)

combined_data.head(10)

,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
0,5,1,1,1,2,1.0,3,1,1,2
1,5,4,4,5,7,10.0,3,2,1,2
2,3,1,1,1,2,2.0,3,1,1,2
3,6,8,8,1,3,4.0,3,7,1,2
4,4,1,1,3,2,1.0,3,1,1,2
5,8,10,10,8,7,10.0,9,7,1,4
6,1,1,1,1,2,10.0,3,1,1,2
7,2,1,2,1,2,1.0,3,1,1,2
8,2,1,1,1,2,1.0,1,1,5,2
9,4,2,1,1,2,1.0,2,1,1,2

In [ ]:
combined_data.describe()

,Clump_thickness,Uniformity_of_cell_size,Uniformity_of_cell_shape,Marginal_adhesion,Single_epithelial_cell_size,Bare_nuclei,Bland_chromatin,Normal_nucleoli,Mitoses,Class
count,699.000000,699.000000,699.000000,699.000000,699.000000,683.000000,699.000000,699.000000,699.000000,699.000000
mean,4.417740,3.134478,3.207439,2.806867,3.216023,3.544656,3.437768,2.866953,1.589413,2.689557
std,2.815741,3.051459,2.971913,2.855379,2.214300,3.643857,2.438364,3.053634,1.715078,0.951273
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,1.000000,2.000000
50%,4.000000,1.000000,1.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,2.000000
75%,6.000000,5.000000,5.000000,4.000000,4.000000,6.000000,5.000000,4.000000,1.000000,4.000000
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,4.000000

In [ ]:
combined_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump_thickness              699 non-null    int64
 1   Uniformity_of_cell_size      699 non-null    int64
 2   Uniformity_of_cell_shape     699 non-null    int64
 3   Marginal_adhesion            699 non-null    int64
 4   Single_epithelial_cell_size  699 non-null    int64
 5   Bare_nuclei                  683 non-null    float64
 6   Bland_chromatin              699 non-null    int64
 7   Normal_nucleoli              699 non-null    int64
 8   Mitoses                      699 non-null    int64
 9   Class                        699 non-null    int64
dtypes: float64(1), int64(9)
memory usage: 54.7 KB

In [ ]:
df_cleaned = combined_data.dropna()

In [ ]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 683 entries, 0 to 698
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Clump_thickness              683 non-null    int64
 1   Uniformity_of_cell_size      683 non-null    int64
 2   Uniformity_of_cell_shape     683 non-null    int64
 3   Marginal_adhesion            683 non-null    int64
 4   Single_epithelial_cell_size  683 non-null    int64
 5   Bare_nuclei                  683 non-null    float64
 6   Bland_chromatin              683 non-null    int64
 7   Normal_nucleoli              683 non-null    int64
 8   Mitoses                      683 non-null    int64
 9   Class                        683 non-null    int64
dtypes: float64(1), int64(9)
memory usage: 58.7 KB

In [ ]:
combined_data['Class'].value_counts()

Class
2    458
4    241
Name: count, dtype: int64

In [ ]:
X_clean = X.dropna()
y_clean = y.loc[X_clean.index]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_clean, y_clean, test_size=0.2, random_state=42, stratify=y_clean)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
mlp = MLPClassifier(hidden_layer_sizes=(64, 32),max_iter=1000, random_state=42)

In [ ]:
mlp.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1124: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42)

In [ ]:
y_pred = mlp.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 95.62%

In [ ]:
class_report = classification_report(y_test, y_pred)
print("Classification Report:\n", class_report)

Classification Report:
               precision    recall  f1-score   support

           2       0.98      0.96      0.97        89
           4       0.92      0.96      0.94        48

    accuracy                           0.96       137
   macro avg       0.95      0.96      0.95       137
weighted avg       0.96      0.96      0.96       137